install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libxml2-utils

script:
    - xmllint info.xsd --noout
    - xmllint ModuleConfig.xsd --noout
    - find examples/ -name "info.xml" -print0 | xargs -0 -n1 xmllint --noout --schema info.xsd
    - find examples/ -name "ModuleConfig.xml" -print0 | xargs -0 -n1 xmllint --noout --schema ModuleConfig.xsd
